ec_api/apps/api_docs/urls.py
from django.urls import path

from ec_api.apps.api_docs import views

urlpatterns = [
    path("", views.APIDocsHome.as_view(), name="api_docs"),
    path("concepts/", views.APIDocsConcepts.as_view(), name="api_concepts"),
    path(
        "endpoints/",
        views.APIEndpointsView.as_view(),
        name="api_docs_endpoints",
    ),
    path("notes/", views.APINotesView.as_view(), name="api_docs_notes"),
]

ec_api/apps/users/urls.py
from django.contrib.auth import views as auth_views
from django.urls import path
from users import views

app_name = "users"
urlpatterns = [
    path("login/", views.LoginView.as_view(), name="login"),
    path(
        "authenticate/", views.AuthenticateView.as_view(), name="authenticate"
    ),
    path(
        "logout/",
        auth_views.LogoutView.as_view(template_name="users/logout.html"),
        name="logout",
    ),
    path(
        "keys/<int:pk>/delete/",
        views.DeleteAPIKeyView.as_view(),
        name="delete-key",
    ),
    path(
        "keys/<int:pk>/refresh/",
        views.RefreshAPIKeyView.as_view(),
        name="refresh-key",
    ),
    path(
        "details",
        views.UpdateProfileDetailsView.as_view(),
        name="add_profile_details",
    ),
    path(
        "",
        views.ProfileView.as_view(),
        name="profile",
    ),
]

ec_api/urls.py
import debug_toolbar
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("admin/", admin.site.urls),
    path("user/", include("users.urls")),
    path("", include("frontend.urls")),
    path("docs/", include("api_docs.urls")),
    # Debug only
    path("__debug__/", include(debug_toolbar.urls)),
]

ec_api/apps/api_docs/templatetags/blueprint.py
from apiblueprint_view import dm, parser
from apiblueprint_view.views import BASE_STYLES
from django import template
from django.template.loader import render_to_string

register = template.Library()


def make_styles(styles=None):
    styles = BASE_STYLES
    if not isinstance(styles, dict):
        return styles
    for style in styles:
        if (
            style in styles
            and "class" in styles[style]
            and isinstance(styles[style]["class"], str)
        ):
            styles[style]["class"] += " " + styles[style]["class"]
    return styles


class InlineApibpParser(parser.ApibpParser):
    def __init__(
        self,
    ):
        super().__init__("")

    def parse_inline(self, content):
        apibp = content
        if self.process_includes:
            apibp = self._replace_includes(apibp)
        self.api = dm.parse(apibp)
        self._set_host()
        self._post_process(self.api[0])

        return self.api


def do_blueprint(parser, token):
    nodelist = parser.parse(("endblueprint",))
    parser.delete_first_token()
    return BlueprintNode(nodelist)


class BlueprintNode(template.Node):
    def __init__(self, nodelist):
        self.nodelist = nodelist

    def render(self, context):
        parser = InlineApibpParser()
        value = self.nodelist.render(context)
        base_content = f"""FORMAT: 1A

{value}
        """

        return render_to_string(
            "api_docs/default_base.html",
            {
                "root": parser.parse_inline(base_content).content[0],
                "styles": make_styles(),
            },
        )


register.tag("blueprint", do_blueprint)

ec_api/apps/api_docs/views.py
# Create your views here.
import os

from apiblueprint_view.views import ApiBlueprintView
from django.conf import settings
from django.views.generic import TemplateView


class APIDocsHome(TemplateView):
    template_name = "api_docs/home.html"


class APIDocsConcepts(TemplateView):
    template_name = "api_docs/concepts.html"


class BaseAPIDocsBlueprintView(ApiBlueprintView):
    blueprint_base = os.path.join(
        settings.BASE_DIR, "apps/api_docs/blueprints/"
    )

    # template_name = ("api_docs_template.html",)
    styles = {
        "resource": {"class": "card"},
        "resource_group": {"class": "group"},
        "api-description": {"class": "ds-stack-smaller"},
        "method_GET": {"class": "badge success"},
    }

    @property
    def blueprint(self):
        return self.blueprint_base + self.blueprint_file

    def get_template_names(self):
        self.template_name = "api_docs/api_docs_base.html"
        return [self.template_name]


class APIEndpointsView(BaseAPIDocsBlueprintView):
    blueprint_file = "endpoints.apibp"


class APINotesView(BaseAPIDocsBlueprintView):
    blueprint_file = "notes.apibp"

ec_api/apps/api_docs/templates/api_docs/api_docs_base.html
{%  extends "base.html" %}
<title>{% block title %}
  Documentation | Electoral Commission Election information API
{% endblock %}</title>
{% block subnav %}
  <nav class="ds-subnav" aria-label="About">
    <ul>
      <li>
        <a href="{% url "api_docs" %}" aria-current="true">Home</a>
      </li>
      <li>
        <a href="{% url "api_concepts" %}">Concepts</a>
      </li>
      <li>
        <a href="{% url "api_docs_endpoints" %}">Endpoints</a>
      </li>
      <li>
        <a href="{% url "api_docs_notes" %}">Notes</a>
      </li>
    </ul>
  </nav>

{% endblock %}

{% block content %}

  {% block api_docs_content %}
    {% include 'api_docs/docs_parent.html' %}
  {% endblock %}

{% endblock %}

ec_api/apps/api_docs/templates/api_docs/concepts.html
{%  extends "api_docs/api_docs_base.html" %}

{% block api_docs_content %}
  {% load pipeline %}
  {% javascript 'mermaid' %}
  <script>

    mermaid.initialize({
      startOnLoad:true,
      sequence: {
        mirrorActors: false,
        showSequenceNumbers: true
      }
    });
  </script>




  <h1>Overview and concepts</h1>
  <p>This API takes a postcode or UPRN and returns current information about
    elections, councils, candidates and polling stations.
  </p>

  <h3>High level concepts</h3>
  <div class="ds-grid">
    <div>



      <p>It's important to understand that this API returns <em>different types of response</em>
        depending on the postcode entered</p>

      <p>This is because some postcodes are "split" across council areas or
        polling districts, meaning that we need more information than just a postcode
        in order to give accurate responses.</p>

      <p>The additional information we need is the exact UPRN for the property, and
        this is provided as a [list of addresses] if we detect a split postcode.</p>

    </div>
    <div>
      <figure>
        <figcaption>Case 1: Results after address picker shown</figcaption>
        <div class="mermaid">
          sequenceDiagram
          Client->>+API: Postcode lookup to /api/postcode/{postcode}
          API->>+Client: Address picker with UPRNs
          Client->>+API: UPRN lookup to /api/address/{UPRN}
          API->>+Client: Results

        </div>

      </figure>
      <figure>
        <figcaption>Case 2: Results direct from postcode</figcaption>
        <div class="mermaid">
          sequenceDiagram
          Client->>+API: Postcode lookup to /api/postcode/{postcode}
          API->>+Client: Address picker with UPRNs
          Client->>+API: UPRN lookup to /api/address/{UPRN}
          API->>+Client: Results

        </div>

      </figure>

    </div>
  </div>

  <h2>Authentication</h2>
  <div class="ds-grid">
    <div>
      <p>Calls to the API must be authenticated with a valid API key.</p>
      <p>To get a key, please <a href="{% url "users:login" %}">log in or register</a> and create a key.</p>
      <p>To authenticate with a key pass in the <code>token</code> parameter.</p>



    </div>
    <div class="ds-stack-smaller">
      <figure>
        <figcaption>Authenticate with URL param</figcaption>
        <pre>
    curl -X GET https://api.electoralcommission.org.uk/api/[endpoint]/?token=123456'
    </pre>
      </figure>
    </div>
  </div>


  <h2>Errors</h2>
  <div class="ds-grid">
    <div>
      <p>Errors will be reported using HTTP status codes. The body of the error will be formatted as valid JSON
        and will give a description of the error</p>



    </div>
    <div class="ds-stack-smaller">
      <figure>
        <figcaption>Example error response</figcaption>
        <pre>
    { "detail": "Could not geocode from any source" }
    </pre>
      </figure>
    </div>
  </div>

{% endblock %}

ec_api/apps/api_docs/templates/api_docs/home.html
{%  extends "api_docs/api_docs_base.html" %}

{% block api_docs_content %}
  {% load pipeline %}
  {% javascript 'mermaid' %}
  <script>

    mermaid.initialize({
      startOnLoad:true,
      sequence: {
        mirrorActors: false,
        showSequenceNumbers: true
      }
    });
  </script>


  <h1>Election information API v1</h1>
  <p>
    Use the election information API to provide your users with all the information they need to take part in
    elections, all in one place.
  </p>
  <p>
    The API uses postcode information to give voters tailored information on where and when to vote, as well
    as the candidates standing for elections in their area.
  </p>
  <p>
    The service is run by <a href="https://democracyclub.org.uk/">Democracy Club</a>,
    on behalf of the <a href="https://www.electoralcommission.org.uk/">Electoral Commission</a>.
    Democracy Club is a community
    interest company with a mission to ensure everyone has access to quality information on democratic processes,
    particularly on elections. We work together to make sure voters have the latest information on upcoming elections.
  </p>
  <p>This is a new service. Share your feedback and help us shape the next version.</p>

  <h2>What’s available in v1</h2>


  <h3>Latest election name and date</h3>
  <p>Let your users know what elections are coming up in their area. The API will show dates for every type of election,
    from by-elections to general elections. It also tracks if an election has been cancelled.</p>

  <p>Town, parish and community council elections, and referendums, are not included in this version.</p>

  <h3>Electoral registration contact information</h3>
  <p>Help your users with postal and proxy forms, or electoral registration questions. Provide them with the telephone,
    email, and postal address for their local elections team.</p>

  <p>Two addresses can be displayed for Scotland postcodes: one for the electoral registration team, and another for
    the local council.</p>

  <h3>Polling station information</h3>
  <p>Provide users with the location of their polling station ahead of polling day, and in some cases, a map to help
    plan their route.</p>

  <p>We aim to cover every postcode in the UK, but this isn’t always possible. We ask local councils to share this data
    with us. Unfortunately not all councils do.</p>

  <p>Accuracy is also important to us. Polling station data can only be published if it contains no errors.</p>

  <p>If you work at a local authority and would like to provide polling station data, please follow the
    <a href="https://democracyclub.org.uk/projects/polling-stations/upload/">few simple
      steps to export data from your EMS</a>.</p>

  <h3>Candidate information</h3>
  <p>Give your users a heads up on who will be on their ballot paper on polling day. The API will show the name of the
    candidate, and the party they’re standing for.</p>
  <h3>Not available in v1</h3>
  <p>Welsh language support is not included in v1. We are working on this for v2.</p>





{% endblock %}